apiVersion: v1
kind: Namespace
metadata:
  name: bka-jenkins
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: bka-jenkins
spec:
  url: https://charts.jenkins.io
  interval: 5m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bka-jenkins
  namespace: bka-jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: '>=4.0.0'
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: bka-jenkins
  values:
    controller:
      testEnabled: false
      serviceType: LoadBalancer
      adminPassword: admin
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: jenkins.dudenas.work
          paths:
            - path: /
              pathType: Prefix
      #tls:
      #  - hosts:
      #      - clusterpodinfo.dudenas.work
      #    secretName: podinfo-tls